
export const columns = [
  { field: "id", headerName: "ID", width: 33 },
  { field: "registrarId", headerName: "Registrar ID" },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
    cellClassName: "name-column--cell",
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    headerAlign: "left",
    align: "left",
    width: 44
  },
  {
    field: "phone",
    headerName: "Phone Number",
    flex: 1,
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1,
  },
  {
    field: "address",
    headerName: "Address",
    flex: 1,
  },
  {
    field: "city",
    headerName: "City",
    flex: 1,
  },
  {
    field: "zipCode",
    headerName: "Zip Code",
  },
];

export const rows = [
  {
    id: 1,
    name: "Ram gurung ",
    email: "ramgurung@gmail.com",
    age: 35,
    phone: "(665)121-5454",
    address: "Pokhara-14 kudhar",
    city: "Pokhara",
    zipCode: "33700",
    registrarId: 123512,
  },
  {
    id: 2,
    name: "hari bahadur",
    email: "ekloktoma@gmail.com",
    age: 42,
    phone: "9879998756",
    address: "1234 Main Street, lakeside, NY 10001",
    city: "pokhara",
    zipCode: "33700",
    registrarId: 123512,
  },
  {
    id: 3,
    name: "ram karki",
    email: "ramkarki@gmail.com",
    age: 45,
    phone: "982-6739575",
    address: "kathmandu -0 ratnapark",
    city: "pokhara",
    zipCode: "87281",
    registrarId: 4132513,
  },
  {
    id: 4,
    name: "ram kc",
    email: "ramkc@gmail.com",
    age: 16,
    phone: "(9214256742",
    address: "lalitpur 15 pokhara",
    city: "lalitpir",
    zipCode: "15551",
    registrarId: 123512,
  },
  {
    id: 4,
    name: "ram kc",
    email: "ramkc@gmail.com",
    age: 16,
    phone: "(9214256742",
    address: "lalitpur 15 pokhara",
    city: "lalitpir",
    zipCode: "15551",
    registrarId: 123512,
  },
  {
    id: 4,
    name: "ram kc",
    email: "ramkc@gmail.com",
    age: 16,
    phone: "(9214256742",
    address: "lalitpur 15 pokhara",
    city: "lalitpir",
    zipCode: "15551",
    registrarId: 123512,
  },
  {
    id: 4,
    name: "ram kc",
    email: "ramkc@gmail.com",
    age: 16,
    phone: "(9214256742",
    address: "lalitpur 15 pokhara",
    city: "lalitpir",
    zipCode: "15551",
    registrarId: 123512,
  },
  {
    id: 4,
    name: "ram kc",
    email: "ramkc@gmail.com",
    age: 16,
    phone: "(9214256742",
    address: "lalitpur 15 pokhara",
    city: "lalitpir",
    zipCode: "15551",
    registrarId: 123512,
  },]